In [1]:
import pandas as pd
import glob

In [2]:
sub_info = []
sub_info.append(glob.glob('data/MARINE_CWBUOY_22453*'))
#sub_info.append(glob.glob('data/MARINE_CWBUOY_22490*'))
sub_info.append(glob.glob('data/MARINE_BUOY_22106*'))

In [3]:
sub_df_list = []
keys = []
for info in sub_info:
    files = []
    pos = 0

    for filename in info:
        print(filename)
        sub_df = pd.read_csv(filename,encoding='euc-kr')
        files.append(sub_df)
        pos = str(sub_df['지점'][0])
        print(pos)

    sub_df = pd.concat(files,axis=0)
    sub_df.sort_values('일시',inplace=True)
    sub_df.reset_index(inplace=True, drop=True)
    sub_df.drop(['지점'],axis=1,inplace=True)
    temp_col_names = []

    temp_date = pos+'_'+'일시'
    keys.append(temp_date)
    
    for col in sub_df.columns:
        print(col)
        temp_col_names.append(pos+'_'+str(col))
            
    sub_df.columns = temp_col_names                        
    sub_df.info()
    
    sub_df[temp_date] = sub_df[temp_date].apply(lambda x:x.replace('-','').replace(' ','').replace(':','')[:-2])
    sub_df.drop_duplicates(subset=[temp_date],keep='first',inplace=True)
    
    sub_df_list.append(sub_df)

data/MARINE_CWBUOY_22453_HR_2014_2014_2016.csv
22453
data/MARINE_CWBUOY_22453_HR_2015_2015_2016.csv
22453
data/MARINE_CWBUOY_22453_HR_2016_2016_2018.csv
22453
data/MARINE_CWBUOY_22453_HR_2017_2017_2018.csv
22453
일시
수온(°C)
최대파고(m)
유의파고(m)
평균파고(m)
파주기(sec)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34063 entries, 0 to 34062
Data columns (total 6 columns):
22453_일시          34063 non-null object
22453_수온(°C)      33166 non-null float64
22453_최대파고(m)     33716 non-null float64
22453_유의파고(m)     33716 non-null float64
22453_평균파고(m)     33716 non-null float64
22453_파주기(sec)    33718 non-null float64
dtypes: float64(5), object(1)
memory usage: 1.6+ MB
data/MARINE_BUOY_22106_HR_2014_2014_2015.csv
22106
data/MARINE_BUOY_22106_HR_2015_2015_2018.csv
22106
data/MARINE_BUOY_22106_HR_2016_2016_2018.csv
22106
data/MARINE_BUOY_22106_HR_2017_2017_2018.csv
22106
GUST풍속 1(m/s)
GUST풍속(m/s)
기온(°C)
수온(°C)
습도(%)
유의파고(m)
일시
최대파고(m)
파주기(sec)
파향(deg)
평균파고(m)
풍속(m/s)
풍속1(m/s)
풍향(deg)
풍향1(deg)
현지기압(hPa)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34556 entries, 0 to 34555
Data columns (total 16 columns):
22106_GUST풍속 1(m/s)    7766 non-null float64
22106_GUST풍속(m/s)      25453 non-null float64
22106_기온(°C)           34205 non-null float64
22106_수온(°C)           34517 non-null float64
22106_습도(%)            33878 non-null float64
22106_유의파고(m)          34462 non-null float64
22106_일시               34556 non-null object
22106_최대파고(m)          34548 non-null float64
22106_파주기(sec)         34488 non-null float64
22106_파향(deg)          34525 non-null float64
22106_평균파고(m)          34371 non-null float64
22106_풍속(m/s)          25376 non-null float64
22106_풍속1(m/s)         7766 non-null float64
22106_풍향(deg)          25379 non-null float64
22106_풍향1(deg)         7926 non-null float64
22106_현지기압(hPa)        34371 non-null float64
dtypes: float64(15), object(1)
memory usage: 4.2+ MB

In [4]:
df = pd.read_csv('./swell_data_by_hour.csv')
df['hour'] = df['hour'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34992 entries, 0 to 34991
Data columns (total 4 columns):
hour                     34992 non-null object
climate                  34992 non-null object
weather_deterioration    34992 non-null int64
swell                    34392 non-null float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ MB

In [5]:
df.head()

         hour climate  weather_deterioration  swell
0  2014010407       0                      0    0.0
1  2014010408       0                      0    0.0
2  2014010409       0                      0    0.0
3  2014010410       0                      0    0.0
4  2014010411       0                      0    0.0

In [6]:
merged_df = df.copy()
for i,sub_df in enumerate(sub_df_list):
    merged_df = merged_df.merge(sub_df, left_on='hour',right_on=keys[i],how='left')
    merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34992 entries, 0 to 34991
Data columns (total 10 columns):
hour                     34992 non-null object
climate                  34992 non-null object
weather_deterioration    34992 non-null int64
swell                    34392 non-null float64
22453_일시                 33979 non-null object
22453_수온(°C)             33082 non-null float64
22453_최대파고(m)            33632 non-null float64
22453_유의파고(m)            33632 non-null float64
22453_평균파고(m)            33632 non-null float64
22453_파주기(sec)           33634 non-null float64
dtypes: float64(6), int64(1), object(3)
memory usage: 2.9+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 34992 entries, 0 to 34991
Data columns (total 26 columns):
hour                     34992 non-null object
climate                  34992 non-null object
weather_deterioration    34992 non-null int64
swell                    34392 non-null float64
22453_일시                 33979 non-null object
22453_수온(°C)             33082 non-null float64
22453_최대파고(m)            33632 non-null float64
22453_유의파고(m)            33632 non-null float64
22453_평균파고(m)            33632 non-null float64
22453_파주기(sec)           33634 non-null float64
22106_GUST풍속 1(m/s)      7685 non-null float64
22106_GUST풍속(m/s)        25453 non-null float64
22106_기온(°C)             34124 non-null float64
22106_수온(°C)             34436 non-null float64
22106_습도(%)              33797 non-null float64
22106_유의파고(m)            34381 non-null float64
22106_일시                 34475 non-null object
22106_최대파고(m)            34467 non-null float64
22106_파주기(sec)           34407 non-null float64
22106_파향(deg)            34444 non-null float64
22106_평균파고(m)            34290 non-null float64
22106_풍속(m/s)            25376 non-null float64
22106_풍속1(m/s)           7685 non-null float64
22106_풍향(deg)            25379 non-null float64
22106_풍향1(deg)           7845 non-null float64
22106_현지기압(hPa)          34290 non-null float64
dtypes: float64(21), int64(1), object(4)
memory usage: 7.2+ MB

In [7]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34992 entries, 0 to 34991
Data columns (total 26 columns):
hour                     34992 non-null object
climate                  34992 non-null object
weather_deterioration    34992 non-null int64
swell                    34392 non-null float64
22453_일시                 33979 non-null object
22453_수온(°C)             33082 non-null float64
22453_최대파고(m)            33632 non-null float64
22453_유의파고(m)            33632 non-null float64
22453_평균파고(m)            33632 non-null float64
22453_파주기(sec)           33634 non-null float64
22106_GUST풍속 1(m/s)      7685 non-null float64
22106_GUST풍속(m/s)        25453 non-null float64
22106_기온(°C)             34124 non-null float64
22106_수온(°C)             34436 non-null float64
22106_습도(%)              33797 non-null float64
22106_유의파고(m)            34381 non-null float64
22106_일시                 34475 non-null object
22106_최대파고(m)            34467 non-null float64
22106_파주기(sec)           34407 non-null float64
22106_파향(deg)            34444 non-null float64
22106_평균파고(m)            34290 non-null float64
22106_풍속(m/s)            25376 non-null float64
22106_풍속1(m/s)           7685 non-null float64
22106_풍향(deg)            25379 non-null float64
22106_풍향1(deg)           7845 non-null float64
22106_현지기압(hPa)          34290 non-null float64
dtypes: float64(21), int64(1), object(4)
memory usage: 7.2+ MB

In [8]:
merged_df.head()

,hour,climate,weather_deterioration,swell,22453_일시,22453_수온(°C),22453_최대파고(m),22453_유의파고(m),22453_평균파고(m),22453_파주기(sec),...,22106_일시,22106_최대파고(m),22106_파주기(sec),22106_파향(deg),22106_평균파고(m),22106_풍속(m/s),22106_풍속1(m/s),22106_풍향(deg),22106_풍향1(deg),22106_현지기압(hPa)
0,2014010407,0,0,0.0,2014010407,14.3,0.9,0.7,0.4,4.4,...,2014010407,2.0,5.8,352.0,1.0,NaN,8.2,NaN,10.0,1016.5
1,2014010408,0,0,0.0,2014010408,14.1,1.3,1.0,0.6,5.0,...,2014010408,2.1,5.3,356.0,1.0,NaN,8.1,NaN,10.0,1016.7
2,2014010409,0,0,0.0,2014010409,14.0,1.5,1.1,0.7,5.0,...,2014010409,1.9,5.8,339.0,1.0,NaN,7.3,NaN,42.0,1017.1
3,2014010410,0,0,0.0,2014010410,14.0,1.3,1.0,0.6,5.3,...,2014010410,2.3,6.4,353.0,1.0,NaN,8.3,NaN,357.0,1017.6
4,2014010411,0,0,0.0,2014010411,14.0,1.4,1.0,0.6,5.3,...,2014010411,2.5,6.4,2.0,1.0,NaN,8.5,NaN,26.0,1017.8

In [9]:
train_df = merged_df[merged_df['swell'].notnull()]
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34392 entries, 0 to 34991
Data columns (total 26 columns):
hour                     34392 non-null object
climate                  34392 non-null object
weather_deterioration    34392 non-null int64
swell                    34392 non-null float64
22453_일시                 33421 non-null object
22453_수온(°C)             32524 non-null float64
22453_최대파고(m)            33074 non-null float64
22453_유의파고(m)            33074 non-null float64
22453_평균파고(m)            33074 non-null float64
22453_파주기(sec)           33076 non-null float64
22106_GUST풍속 1(m/s)      7614 non-null float64
22106_GUST풍속(m/s)        24998 non-null float64
22106_기온(°C)             33550 non-null float64
22106_수온(°C)             33838 non-null float64
22106_습도(%)              33223 non-null float64
22106_유의파고(m)            33783 non-null float64
22106_일시                 33877 non-null object
22106_최대파고(m)            33869 non-null float64
22106_파주기(sec)           33812 non-null float64
22106_파향(deg)            33846 non-null float64
22106_평균파고(m)            33692 non-null float64
22106_풍속(m/s)            24923 non-null float64
22106_풍속1(m/s)           7614 non-null float64
22106_풍향(deg)            24926 non-null float64
22106_풍향1(deg)           7774 non-null float64
22106_현지기압(hPa)          33695 non-null float64
dtypes: float64(21), int64(1), object(4)
memory usage: 7.1+ MB

In [10]:
test_df = merged_df[merged_df['swell'].isnull()]
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 600 entries, 3216 to 34511
Data columns (total 26 columns):
hour                     600 non-null object
climate                  600 non-null object
weather_deterioration    600 non-null int64
swell                    0 non-null float64
22453_일시                 558 non-null object
22453_수온(°C)             558 non-null float64
22453_최대파고(m)            558 non-null float64
22453_유의파고(m)            558 non-null float64
22453_평균파고(m)            558 non-null float64
22453_파주기(sec)           558 non-null float64
22106_GUST풍속 1(m/s)      71 non-null float64
22106_GUST풍속(m/s)        455 non-null float64
22106_기온(°C)             574 non-null float64
22106_수온(°C)             598 non-null float64
22106_습도(%)              574 non-null float64
22106_유의파고(m)            598 non-null float64
22106_일시                 598 non-null object
22106_최대파고(m)            598 non-null float64
22106_파주기(sec)           595 non-null float64
22106_파향(deg)            598 non-null float64
22106_평균파고(m)            598 non-null float64
22106_풍속(m/s)            453 non-null float64
22106_풍속1(m/s)           71 non-null float64
22106_풍향(deg)            453 non-null float64
22106_풍향1(deg)           71 non-null float64
22106_현지기압(hPa)          595 non-null float64
dtypes: float64(21), int64(1), object(4)
memory usage: 126.6+ KB

In [11]:
merged_df.to_csv('merged_info_data.tsv',sep='\t')